# fly.toml app configuration file generated for react-coinmarketcap-be on 2023-08-31T16:56:00+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "react-coinmarketcap-be"
primary_region = "sin"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
